services:
  client:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

  server:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
