services:
  client:
    build:
      target: development
      args:
        NODE_ENV: development
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development

  server:
    build:
      args:
        NODE_ENV: development
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
