services:
  client:
    image: ghcr.io/chibranche/farigoule-client:${TAG}
    container_name: farigoule-client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=fanfare-farigoule.com
      - LETSENCRYPT_HOST=fanfare-farigoule.com
      - API_BACKEND_URL=${API_BACKEND_URL}
    ports:
      - "${CLIENT_PORT}:80"
    restart: unless-stopped
    networks:
      - farigoule-network
    depends_on:
      - server

  server:
    image: ghcr.io/chibranche/farigoule-server:${TAG}  
    container_name: farigoule-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - farigoule-db-storage:/usr/app/database/
      - farigoule-uploads-storage:/usr/app/public/uploads
    restart: unless-stopped
    networks:
      - farigoule-network

  watchtower:
      image: containrrr/watchtower:latest
      container_name: watchtower
      restart: unless-stopped
      # Intervalle = 300 s (5 min) ; --cleanup supprime l’ancienne image après maj
      # --label-enable : ne touche qu’aux conteneurs marqués ci-dessus
      command: >
        --interval 300
        --cleanup
        --label-enable
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ~/.docker:/config:ro
      environment:
        - TZ=Europe/Paris

volumes:
  farigoule-db-storage:
    external: true
    name: farigoule-db-storage
  farigoule-uploads-storage:
    external : true
    name : farigoule-uploads-storage
networks:
  farigoule-network:
    external: true
    name: farigoule-network